# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4e57943609d360624c3036cbf01700e1a43bc1a8c9c3425e5c5a58f36448fccce772e661334c6ee7c1fb96028b5e6a70ec1e3756699e81882f1ed567c6cbdf7

test:
  secret_key_base: b3bc0d4c32c3cfec23379dee4bf4b4fe33742f6fea815b76264cb3d1ecec24fb05bc129d4844471d5bc57cabfc7d0a30781239c74ab90fedcf202023d0d5a3b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
